makecode:
  target: arcade
  platform: arcade
  home_url: https://arcade.makecode.com/
remote_theme: pages-themes/hacker@v0.2.0
include:
  - assets
  - docs
  - README.md
plugins:
  - jekyll-remote-theme
show_downloads: false
title: Microsoft MicroCode BETA
description: Physical computing for young coders on the micro:bit V2